In [13]:
import pandas as pd
bios = pd.read_csv("C:\\Users\\IBRAHIM\\Documents\\ml-vet-journey\\python\\pand\\bios.csv")
bios_new = bios.copy()
bios_new.query('NOC == "FRANCE"')
bios_new.head()
bios_new[["name","born_date"]]

                        name   born_date
0      Jean-François Blanchy  1886-12-12
1             Arnaud Boetsch  1969-04-01
2               Jean Borotra  1898-08-13
3            Jacques Brugnon  1895-05-11
4               Albert Canet  1878-04-17
...                      ...         ...
99524           Holger Höhne  1970-05-06
99525              Andy Kapp  1967-12-08
99526               Uli Kapp  1971-04-14
99527       Michael Schäffer  1968-04-28
99528          Hirofumi Kudo          19

[99529 rows x 2 columns]